import Head from 'next/head';
import { pretendard } from '@/theme/fonts';
import MainHome from '@/features/home/components/MainHome';
import Header from '@/components/Header/Header';

export default function Home() {
  return (
    <>
      <Head>
        <title>JUNY PORTFOLIO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <style jsx global>{`
        html,
        body {
          font-family: ${pretendard.style.fontFamily};
        }
      `}</style>

      <div style={{ width: '100%' }}>
        <Header />
        {/* home */}
        <MainHome />
      </div>
    </>
  );
}
